<?xml version="1.0" encoding="UTF-8" standalone="no"?><xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmi:version="2.0">
  <ecore:EPackage name="mwcore" nsURI="mwcore">
    <eClassifiers abstract="true" name="WElement" xsi:type="ecore:EClass">
      <eStructuralFeatures eType="#/1/String" lowerBound="1" name="name" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
      <eStructuralFeatures eType="#/1/String" lowerBound="1" name="description" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
      <eStructuralFeatures eOpposite="#/0/WModel/ownedElement" eType="#/0/WModel" lowerBound="1" name="model" ordered="false" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WModel" xsi:type="ecore:EClass">
      <eStructuralFeatures containment="true" eOpposite="#/0/WElement/model" eType="#/0/WElement" name="ownedElement" upperBound="-1" xsi:type="ecore:EReference"/>
      <eStructuralFeatures containment="true" derived="true" eType="#/0/WModelRef" lowerBound="1" name="wovenModel" ordered="false" upperBound="-1" xsi:type="ecore:EReference">
        <eAnnotations source="referencedModel"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WRef" xsi:type="ecore:EClass">
      <eStructuralFeatures eType="#/1/String" lowerBound="1" name="ref" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WRef" name="WModelRef" xsi:type="ecore:EClass">
      <eStructuralFeatures containment="true" eOpposite="#/0/WElementRef/modelRef" eType="#/0/WElementRef" name="ownedElementRef" ordered="false" upperBound="-1" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WRef" name="WElementRef" xsi:type="ecore:EClass">
      <eStructuralFeatures eOpposite="#/0/WModelRef/ownedElementRef" eType="#/0/WModelRef" lowerBound="1" name="modelRef" ordered="false" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WAssociation" xsi:type="ecore:EClass">
      <eStructuralFeatures containment="true" eOpposite="#/0/WAssociationEnd/association" eType="#/0/WAssociationEnd" lowerBound="1" name="associationEnd" ordered="false" upperBound="-1" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WAssociationEnd" xsi:type="ecore:EClass">
      <eStructuralFeatures eOpposite="#/0/WAssociation/associationEnd" eType="#/0/WAssociation" lowerBound="1" name="association" ordered="false" xsi:type="ecore:EReference"/>
      <eStructuralFeatures eType="#/0/WLink" lowerBound="1" name="relatedLink" ordered="false" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WLink" xsi:type="ecore:EClass">
      <eStructuralFeatures containment="true" eOpposite="#/0/WLink/parent" eType="#/0/WLink" name="child" upperBound="-1" xsi:type="ecore:EReference"/>
      <eStructuralFeatures eOpposite="#/0/WLink/child" eType="#/0/WLink" lowerBound="1" name="parent" ordered="false" xsi:type="ecore:EReference"/>
      <eStructuralFeatures containment="true" derived="true" eOpposite="#/0/WLinkEnd/link" eType="#/0/WLinkEnd" lowerBound="1" name="end" ordered="false" upperBound="-1" xsi:type="ecore:EReference">
        <eAnnotations source="annotatedModelElement"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers abstract="true" eSuperTypes="#/0/WElement" name="WLinkEnd" xsi:type="ecore:EClass">
      <eStructuralFeatures eOpposite="#/0/WLink/end" eType="#/0/WLink" lowerBound="1" name="link" ordered="false" xsi:type="ecore:EReference"/>
      <eStructuralFeatures eType="#/0/WElementRef" lowerBound="1" name="element" ordered="false" xsi:type="ecore:EReference"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes" nsURI="PrimitiveTypes">
    <eClassifiers instanceClassName="java.lang.Boolean" name="Boolean" xsi:type="ecore:EDataType"/>
    <eClassifiers instanceClassName="java.lang.Integer" name="Integer" xsi:type="ecore:EDataType"/>
    <eClassifiers instanceClassName="java.lang.String" name="String" xsi:type="ecore:EDataType"/>
  </ecore:EPackage>
  <ecore:EPackage name="mmw_annotation" nsURI="mmw_annotation">
    <eClassifiers eSuperTypes="#/0/WModel" name="AnnotationModel" xsi:type="ecore:EClass">
      <eStructuralFeatures containment="true" eType="#/2/Annotation" name="contents" upperBound="-1" xsi:type="ecore:EReference">
        <eAnnotations source="ownedElement "/>
      </eStructuralFeatures>
      <eStructuralFeatures containment="true" eType="#/2/AnnotatedModel" lowerBound="1" name="referencedModel" ordered="false" xsi:type="ecore:EReference">
        <eAnnotations source="wovenModel"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers eSuperTypes="#/0/WModelRef" name="AnnotatedModel" xsi:type="ecore:EClass">
      <eAnnotations source="welementRefType:AnnotatedModelElementRef"/>
    </eClassifiers>
    <eClassifiers eSuperTypes="#/0/WElementRef" name="AnnotatedModelElementRef" xsi:type="ecore:EClass">
      <eAnnotations source="wmodelRefType:AnnotatedModel"/>
    </eClassifiers>
    <eClassifiers eSuperTypes="#/0/WLink" name="Annotation" xsi:type="ecore:EClass">
      <eStructuralFeatures eType="#/2/TestType" lowerBound="1" name="enumTest" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
      <eStructuralFeatures eType="#/2/Annotation" name="teste" ordered="false" upperBound="-1" xsi:type="ecore:EReference"/>
      <eStructuralFeatures containment="true" eType="#/2/Property" name="properties" upperBound="-1" xsi:type="ecore:EReference"/>
      <eStructuralFeatures containment="true" eType="#/2/AnnotatedModelElement" lowerBound="1" name="annotatedModelElement" ordered="false" upperBound="-1" xsi:type="ecore:EReference">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers eSuperTypes="#/0/WLinkEnd" name="AnnotatedModelElement" xsi:type="ecore:EClass"/>
    <eClassifiers name="TestType" xsi:type="ecore:EEnum">
      <eLiterals name="http://www.w3.org/2001/XMLSchema#string" value="1"/>
      <eLiterals name="http://www.w3.org/2001/XMLSchema#nonNegativeInteger" value="2"/>
      <eLiterals name="http://www.w3.org/2001/XMLSchema#boolean" value="3"/>
      <eLiterals name="http://www.w3.org/2001/XMLSchema#integer" value="4"/>
    </eClassifiers>
    <eClassifiers name="Property" xsi:type="ecore:EClass">
      <eStructuralFeatures eType="#/1/String" lowerBound="1" name="key" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
      <eStructuralFeatures eType="#/1/String" lowerBound="1" name="value" ordered="false" unique="false" xsi:type="ecore:EAttribute"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>