<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:WS_WSDLv1="http://WSDLv1">
  <WS_WSDLv1:Definitions name="POPService">
    <portType>
      <operation name="receivePO">
        <input message="/0/@message.0"/>
      </operation>
    </portType>
    <portType>
      <operation name="receivePOCallBack">
        <output message="/0/@message.1"/>
      </operation>
    </portType>
    <message name="POMessage">
      <part type="/0/@types/@schema.0/@complexType.0"/>
    </message>
    <message name="POMessageAck">
      <part elementImported="/1"/>
      <part type="/0/@types/@schema.0/@simpleType.0"/>
    </message>
    <types>
      <schema>
        <simpleType name="TimeStamp">
          <restriction primitiveType="date"/>
        </simpleType>
        <complexType name="PODocument">
          <sequenceDef>
            <element primitiveType="string" name="OrderInfo"/>
            <element primitiveType="string" name="DeliveryInfo" minOccurs="0"/>
            <element name="TimeStamp" type="/0/@types/@schema.0/@simpleType.0"/>
          </sequenceDef>
        </complexType>
      </schema>
    </types>
  </WS_WSDLv1:Definitions>
  <WS_WSDLv1:ElementImported name="string" url="http://www.w3.org/2001/ XMLSchema" part="/0/@message.1/@part.0"/>
</xmi:XMI>
